# Generated by Django 3.2 on 2024-04-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('roll_no', models.TextField(max_length=10, unique=True)),
                ('age', models.TextField(max_length=3)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.TextField(max_length=8)),
                ('mobile_no', models.TextField(max_length=10)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
    ]
